[package]
name = "prometheus-http-query"
version = "0.1.0"
authors = ["Peter Sebastian Puetz <peter.puetz@itenos.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_test = "1"
tokio-test = "0.4"