[package]
name = "prometheus-http-query"
version = "0.4.0"
authors = ["Peter Sebastian Pütz <ppuetz@protonmail.com>"]
edition = "2018"
repository = "https://github.com/puetzp/prometheus-http-query"
documentation = "https://docs.rs/prometheus-http-query"
readme = "README.md"
license = "MIT"
description = "Prometheus HTTP API client"
keywords = [ "prometheus", "promql", "api" ]

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2.2"
time = { version = "0.3.7", features = ["parsing", "macros"] }

[dev-dependencies]
serde_test = "1"
tokio-test = "0.4"
tokio = { version = "1.16", features = ["macros", "rt"] }
