[package]
name = "prometheus-http-query"
version = "0.5.2"
authors = ["Peter Sebastian Pütz <ppuetz@protonmail.com>"]
edition = "2018"
repository = "https://github.com/puetzp/prometheus-http-query"
documentation = "https://docs.rs/prometheus-http-query"
readme = "README.md"
license = "MIT"
description = "Prometheus HTTP API client"
keywords = [ "prometheus", "prometheus-http-api", "promql", "api", "reqwest" ]

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = { version = "2.2", features = ["serde"] }
time = { version = "0.3.9", features = ["parsing", "macros"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
